### PR TITLE
MODIFIED: add delete todo for handling delete

### PR DESCRIPTION
**Pull request by afrianjunior**
### Description

Hai Adi, sorry i try to add method delete for handling delete todo.

What do you think about that?

### CODE REVIEW

**Comment by adiatma9024** [comment]
Hi, jun, i think you should pull request for the new update in this repo, because i have done to add delete method also.

**Comment by adiatma9024** [comment]
Please resolve this conflict with merge with new update.

**Comment by afrianjunior** [comment]
Okey Adi, im so sorry, and immedietly i try to resolve this conflict

**Comment by adiatma9024** [comment]
Okey, jun thanks....

**Pull request merged**
